### ISSUE TITLE
Slime Chunk detection doesnt work

### ISSUE THREAD

**Issue by Gizmolefou** [wesserboy/Overlays-MC-#1]
Hi,

First thanks for your work, you deliver a very nice mod.
I think the slime chunk detection is ko : I slabed all slime chunks in my cave but I saw slimes spawn in other chunks ...

++
Giz

**Comment by wesserboy** [comment]
Thanks for letting me know!
I have found the issue, a fix for singleplayer should be pretty easy, multiplayer will be a little bit trickier. Worst case I'll have to disable the overlay when playing on a server.
