### ISSUE TITLE
Update to 1.14?

### ISSUE THREAD

**Issue by ultraflame4** [wesserboy/Overlays-MC-#2]
Are You going to update this mod to 1.14 please lemme know

if no can you recommend me other mods that have the bow aim

**Comment by wesserboy** [comment]
I am working on a port to 1.14, I just haven't pushed it to the repo yet.
I can't give an ETA, but I'll close this issue once I'm done with the port. 
If you are subscribed to this thread you should get a notification once I do.

**Comment by ultraflame4** [comment]
oh thanks
